### ISSUE TITLE
Request for providing the raw datasets

### ISSUE THREAD

**Issue by WilliamYi96** [haozzh/FedCR#1]
Hi @haozzh 

There seems to be no `Folder' or any other `Data' folder containing the used dataset. Could you please share it?

**Comment by haozzh** [comment]
Hello, kindly execute the main_fed.py file directly. This action will trigger the automatic download and preprocessing of the dataset into a non-iid format. For more details on the preprocessing steps, please refer to utills/utils_dataset.py.

**Comment by WilliamYi96** [comment]
Thank you, it works!
